### ISSUE TITLE
python 3.12 wheels on windows and macOS

### ISSUE THREAD

**Issue by laggykiller** [thewh1teagle/rookie#6]
It seems like python 3.12 wheels are only available for linux: https://pypi.org/project/rookiepy/#files

Is it possible to provide python 3.12 wheels on windows and macOS? Thanks.

---
Edit:

Seems like python3.12 was not present on the runner for the latest release: https://github.com/thewh1teagle/rookie/actions/runs/6435145142/job/17475799007#step:4:247

Github runner image with python 3.12 is still prerelease (https://github.com/actions/runner-images/releases/tag/win22%2F20231005.1), so your runner did not have python3.12 on it

You can wait about 1 week for github runner with python 3.12 to be released and fully rolled out (https://github.com/actions/runner-images#available-images), by then python 3.12 wheels should be built the next time you run github action without further modifications, or you can modify github action to do this without further waiting:
```
- name: Set up Python 3.12
  uses: actions/setup-python@v4
  with:
    python-version: "3.12"
    allow-prereleases: true
```
